//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.01 at 11:06:00 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://certificate.com/ocsp", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.certificate.ocsp;
