<<<<<<< HEAD
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.21 at 04:45:53 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://certificate.com/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.certificate.user;
=======
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.21 at 07:36:57 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://certificate.com/user", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.certificate.user;
>>>>>>> 2ddede3b0200f46eebb4d667313a7827ce3e1cba
